{{- if .Values.webhookRelay.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "keel.name" . }}-webhookrelay
  namespace: kube-system
  labels:
    app: {{ template "keel.name" . }}
    chart: {{ template "keel.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  key: {{ .Values.webhookRelay.key | b64enc }}
  secret:  {{ .Values.webhookRelay.secret | b64enc }}
{{- end }}
