{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "keel.name" . }}
  namespace: kube-system
  labels:
    app: {{ template "keel.name" . }}
    chart: {{ template "keel.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: 9300
      protocol: TCP
      name: keel
  selector:
    app: {{ template "keel.name" . }}
  sessionAffinity: None
{{- end }}
