apiVersion: v1
description: Installs the Cloudflare Warp Ingress Controller
home: https://warp.cloudflare.com/
maintainers:
- email: rmocius@gmail.com
  name: rimusz
name: cloudflare-warp-ingress
version: 0.1.5
appVersion: 0.4.0
