# Default values for cloudflare-warp-ingress

replicaCount: 1

image:
  repository: quay.io/stackpoint/warp-controller
  tag: 0.4.0
  pullPolicy: Always

# The Cloudflare Warp cert must be encoded with base64
# e.g. `--set cert=$(cat cloudflare-warp.pem | base64)`
# or paste base64 encoded data below
cert: ""

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

rbac:
  install: false
  serviceAccount: cloudflare-warp
  roleName: cloudflare-warp
