apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "flink-demo.fullname" . }}-actor
  labels:
    app: {{ template "flink-demo.name" . }}
    chart: {{ template "flink-demo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "flink-demo.name" . }}-actor
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "flink-demo.name" . }}-actor
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-actor
          image: "{{ .Values.actor.image.repository }}:{{ .Values.actor.image.tag }}"
          imagePullPolicy: {{ .Values.actor.image.pullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
