apiVersion: v1
name: keel
description: Open source, tool for automating Kubernetes deployment updates. Keel is stateless, robust and lightweight.
version: 0.2.1
# Note that we use appVersion to get images tag, so make sure this is correct.
appversion: 0.9.5
keywords:
- kubernetes deployment
- helm release
- continuous deployment
home: https://keel.sh
sources:
- https://github.com/keel-hq/keel
maintainers:
- name: rimusz
  email: rmocius@gmail.com
- name: rusenask
  email: karolis.rusenas@gmail.com
engine: gotpl
